// Optimized Vuetify configuration for better bundle size
// IMPORTANT: Before modifying component imports, see VUETIFY_CHECKLIST.md
// to prevent icon display and component rendering issues
import 'vuetify/styles'
import '@mdi/font/css/materialdesignicons.css'
import 'material-design-icons-iconfont/dist/material-design-icons.css'
import { createVuetify } from 'vuetify'
import { aliases, mdi } from 'vuetify/iconsets/mdi'
import { aliases as aliases_md, md } from 'vuetify/iconsets/md'

// Import only the components we actually use instead of all components
import {
  VApp,
  VMain,
  VContainer,
  VRow,
  VCol,
  VCard,
  VCardTitle,
  VCardText,
  VCardActions,
  VBtn,
  VIcon,
  VChip,
  VChipGroup,
  VList,
  VListItem,
  VListItemTitle,
  VListItemSubtitle,
  VNavigationDrawer,
  VAppBar,
  VAppBarNavIcon,
  VAppBarTitle,
  VToolbar,
  VToolbarTitle,
  VSpacer,
  VAlert,
  VDialog,
  VSheet,
  VDivider,
  VLabel,
  VTooltip,
  VProgressLinear,
  VProgressCircular,
  VResponsive,
  VExpandTransition,
  VBadge,
  VAvatar,
  VTimeline,
  VTimelineItem,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelTitle,
  VExpansionPanelText,
  VTextField,
  VSelect,
  VDataTable,
  VBtnToggle,
  VBtnGroup,
  VMenu,
  VSwitch,
  VTabs,
  VTab,
  VWindow,
  VWindowItem,
} from 'vuetify/components'

// Import only directives we use
import { Ripple } from 'vuetify/directives'

const vuetify = createVuetify({
  components: {
    VApp,
    VMain,
    VContainer,
    VRow,
    VCol,
    VCard,
    VCardTitle,
    VCardText,
    VCardActions,
    VBtn,
    VIcon,
    VChip,
    VChipGroup,
    VList,
    VListItem,
    VListItemTitle,
    VListItemSubtitle,
    VNavigationDrawer,
    VAppBar,
    VAppBarNavIcon,
    VAppBarTitle,
    VToolbar,
    VToolbarTitle,
    VSpacer,
    VAlert,
    VDialog,
    VSheet,
    VDivider,
    VLabel,
    VTooltip,
    VProgressLinear,
    VProgressCircular,
    VResponsive,
    VExpandTransition,
    VBadge,
    VAvatar,
    VTimeline,
    VTimelineItem,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelTitle,
    VExpansionPanelText,
    VTextField,
    VSelect,
    VDataTable,
    VBtnToggle,
    VBtnGroup,
    VMenu,
    VSwitch,
    VTabs,
    VTab,
    VWindow,
    VWindowItem,
  },
  directives: {
    Ripple,
  },
  icons: {
    defaultSet: 'mdi',
    aliases: {
      ...aliases,
      ...aliases_md,
      menu: 'mdi-menu',
    },
    sets: {
      mdi,
      md,
    },
  },
  theme: {
    defaultTheme: 'dark',
  },
})

export default vuetify
